-- Schema for Compliance-First AI SNS Agent

-- Table: users (Stores OAuth tokens and Metadata)
CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL PRIMARY KEY,
    meta_asid VARCHAR(255) UNIQUE NOT NULL, -- App Scoped ID from Facebook
    access_token TEXT NOT NULL,             -- Encrypted ideally, but plain for prototype
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: drafts (Stores content generated by AI before publishing)
CREATE TABLE IF NOT EXISTS drafts (
    id SERIAL PRIMARY KEY,
    image_url TEXT NOT NULL,                -- S3 Presigned URL or Key
    caption TEXT,
    hashtags TEXT,
    status VARCHAR(50) DEFAULT 'PENDING',   -- PENDING, APPROVED, PUBLISHED, REJECTED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ig_container_id VARCHAR(255),           -- Instagram Media Container ID
    ig_media_id VARCHAR(255)                -- Published Media ID
);

-- Table: performance_log (Compliance: Anonymized Insights)
CREATE TABLE IF NOT EXISTS performance_log (
    insight_id SERIAL PRIMARY KEY,
    media_id VARCHAR(255),
    metrics JSONB,                          -- Stored as JSON for flexibility
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
